import React, { useState } from "react";
import styles from "./forgetpassword.module.scss";
import Image from "next/image";
import Link from "next/link";
import Router from "next/router";
import Head from "next/head";
const ForgetPassword = () => {
  const [isEmail, setIsEmail] = useState("");
  const [activeEmailInput, setActiveEmailInput] = useState(true);
  const [activePinInput, setActivePinInput] = useState(false);
  const [activePassword, setActivePassword] = useState(false);
  const handleSentPin = () => {
    setActiveEmailInput(false);
    setActivePinInput(true);
  };
  const handleSubmitPin = () => {
    setActivePinInput(false);
    setActivePassword(true);
  };

  const handleSubmitValue = () => {
    Router.push("/");
  };
  return (
    <>
      <Head>
        <title>Forget Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.container}>
          <div className={styles.forgetPassword}>
            <div className={styles.left}>
              <div className={styles.profile}>
                <div className={styles.image}>
                  <Image
                    src="/profile.svg"
                    alt="Profile Pic"
                    width={200}
                    height={50}
                  />
                </div>
                <div className={styles.heading}>Reset Password</div>
              </div>

              <div className={styles.form}>
                {activeEmailInput && (
                  <>
                    <div className={styles.InputDiv}>
                      <input type="email" placeholder="Email *" />
                    </div>
                    {/* <div className={styles.InputDiv}>
                    <input type="password" placeholder="New Password *" />
                  </div> */}

                    <div className={styles.submitbtn}>
                      <button type="submit" onClick={handleSentPin}>
                        Submit
                      </button>
                    </div>
                  </>
                )}
                {activePinInput && (
                  <>
                    {/* <div className={styles.InputDiv}>
                    <input type="email" placeholder="Email *" />
                  </div> */}
                    <div className={styles.InputDiv}>
                      <input type="text" placeholder="Enter Pin Code *" />
                    </div>

                    <div className={styles.submitbtn}>
                      <button type="submit" onClick={handleSubmitPin}>
                        Submit
                      </button>
                    </div>
                  </>
                )}
                {activePassword && (
                  <>
                    <div className={styles.InputDiv}>
                      <input type="password" placeholder="New Password *" />
                    </div>
                    <div className={styles.InputDiv}>
                      <input type="password" placeholder="Confirm Password *" />
                    </div>

                    <div className={styles.submitbtn}>
                      <button type="submit" onClick={handleSubmitValue}>
                        Submit
                      </button>
                    </div>
                  </>
                )}
                <div className={styles.signup}>
                  Have an Account ? &nbsp;
                  <Link href="/">Login</Link>
                </div>
              </div>
            </div>
            <div className={styles.right}>
              <div className={styles.bgimage}>
                <Image
                  src="/Rectangle.svg"
                  width={330}
                  height={490}
                  alt="Pic"
                />
              </div>
              <div className={styles.profileman}>
                <Image
                  src="/profile-man.svg"
                  width={200}
                  height={200}
                  alt="Pic"
                />
              </div>
              <div className={styles.lampshade}>
                <Image src="/lampshade.svg" width={90} height={100} alt="Pic" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ForgetPassword;
